# Generated by Django 4.1.4 on 2023-02-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0004_officialdgp'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='post',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
