# Generated by Django 4.1.4 on 2023-04-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0008_medicalrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecords',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
