# Generated by Django 4.1.5 on 2023-05-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crimeapp", "0012_alter_firmod_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.FloatField()),
                ("long", models.FloatField()),
                ("address", models.TextField()),
            ],
        ),
    ]
