# Generated by Django 4.1.5 on 2023-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crimeapp", "0020_grievence"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievence",
            name="sender",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
