# Generated by Django 4.1.5 on 2023-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crimeapp", "0022_alter_visitor_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="end_date",
            field=models.CharField(max_length=200),
        ),
    ]
