# Generated by Django 4.1.5 on 2023-05-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crimeapp", "0023_alter_visitor_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="duty",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
