# Generated by Django 4.1.5 on 2023-05-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crimeapp", "0024_duty_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="achievements/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("text", models.CharField(max_length=200)),
            ],
        ),
    ]
