# Generated by Django 4.2.1 on 2023-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0026_achievement_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=300)),
                ('murder', models.CharField(max_length=300)),
                ('rape', models.CharField(max_length=300)),
                ('theft', models.CharField(max_length=300)),
                ('others', models.CharField(max_length=300)),
                ('total', models.CharField(max_length=300)),
                ('average', models.CharField(max_length=300)),
                ('future', models.CharField(max_length=300)),
                ('nextplace', models.CharField(max_length=300)),
                ('ndays', models.CharField(max_length=300)),
            ],
        ),
    ]
